spring.application.name=qr-menu-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/qrmenu
spring.datasource.username=qruser
spring.datasource.password=qrpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

jwt.secret=3f8a2b1c9d4e7f6a0b5c8d2e1f4a7b3c9d6e2f5a8b1c4d7e0f3a6b9c2d5e8f1a
jwt.expiration=86400000

app.customer-base-url=http://192.168.1.72:5173