spring.application.name=qr-menu-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/qrmenu
spring.datasource.username=qruser
spring.datasource.password=qrpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true